# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: bc66c97ceff3b9aa85e3a078e87c87692315ddd31332194c879a571e42f78b8a738f1fd2cd944d38097691cef5231cf19099af4b4be57ff30f989a19212d51e4

test:
  secret_key_base: 8cb19b4f53aa52b971e6200d2e5beafb3fa0779cc1264334d784be654acdf1c2b542700041ab9f50de2ced0d74341e617a3a9dc0f666240894f72e841e9be476

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
